name: Build And Deploy To Aliyun Ecs

on:
  release:
    types: [created]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Using Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v4.0.1
      with:
        node-version: ${{matrix.node-version}}
    - name: Transfer .env.production file
      run: |
        echo "DATABASE_TYPE=${{secrets.DATABASE_TYPE}}" >> .env.production
        echo "DATABASE_PORT=${{secrets.DATABASE_PORT}}" >> .env.production
        echo "DATABASE_HOST=${{secrets.DATABASE_HOST}}" >> .env.production
        echo "DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}}" >> .env.production
        echo "DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}" >> .env.production
        echo "DATABASE_DATABASE=${{secrets.DATABASE_DATABASE}}" >> .env.production
        echo "" >> .env.production
        echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> .env.production
        echo "" >> .env.production
        echo "AVATAR_DIR=/usr/local/chat/avatars" >> .env.production
        echo "AVATAR_URL=http://imjoye.chat/avatars" >> .env.production
        echo "" >> .env.production
        echo "REDIS_HOST=127.0.0.1"
        echo "REDIS_PORT=6379"
        echo "REDIS_DB=0"
        echo "" >> .env.production
        echo "PASS=${{secrets.PASS}} >> .env.production"
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/usr/local/chat/nestjs-chat"
          EXCLUDE: "node_modules/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            cd /usr/local/chat/nestjs-chat
            cnpm run run-migration
            cnpm install
            cnpm run build
            ls -al
            pm2 restart pm2.json --name nestjs-chat